---
- name: Create an EC2 instance in AWS
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        key_name: mykey
        instance_type: t2.micro
        region: us-east-1
        image_id: ami-0e86e20dae9224db8  # Ubuntu AMI, adjust based on your region
        wait: yes
        count: 1
        security_group: default

        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

        tags:
          Name: MyAnsible_CreatedEC2
      register: ec2_instance

    - name: Output the created instance details
      debug:
        var: ec2_instance
