---
- name: Create an EC2 instance in AWS
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        key_name: mykeys
        instance_type: t2.micro
        region: us-east-1
        image_id: ami-0c55b159cbfafe1f0  # Ubuntu AMI, adjust based on your region
        wait: yes
        count: 1
        security_group: default

        instance_tags:
          Name: MyAnsible_CreatedEC2
      register: ec2_instance

    - name: Output the created instance details
      debug:
        var: ec2_instance
