pipeline{
    agent any

    stages{

        stage("checkout"){
            steps{  
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/irfanmestri/projects.git']])

            }
        }
        stage("execute"){
            steps{
                ansiblePlaybook playbook: 'EC2_Instance(Ansible%26Jenkins)/create-EC2.yml'
            }
        }

    }
}